variant:
  - vtk
  - core

CONDA_BUILD_SYSROOT:
 - /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk       # [osx]

c_compiler:
 - vs2022                     # [win]
 
cxx_compiler:
 - vs2022                     # [win]